export const INDICE = [
  ["tokens", "Colores y tipografía"],
  ["marca", "Marca y kit"],
  ["acciones", "Botones"],
  ["formularios", "Campos y opciones"],
  ["selectores", "Selectores"],
  ["media-picker", "Selector de medios"],
  ["creador", "Creador"],
  ["personajes", "Personajes"],
  ["presets", "Presets y prompt"],
  ["direccion", "Dirección del clip"],
  ["productos", "Producto y acción"],
  ["lugares", "Lugares"],
  ["canto", "Cantar con audio propio"],
  ["proyectos", "Proyectos y plan"],
  ["anuncio", "Estrategia del anuncio"],
  ["reparto", "Dos personajes"],
  ["montaje", "Montaje y exportación"],
  ["formatos", "Formatos, encuadre y versiones"],
  ["conversion", "De Crear a un proyecto"],
  ["cuentas", "Cuentas"],
  ["datos", "Tus datos"],
  ["secretos", "Secretos"],
  ["alertas", "Alertas"],
  ["estados", "Estados y presupuesto"],
  ["controles", "Controles previos"],
  ["generacion", "Coste y trabajos"],
  ["modelos", "Catálogo de modelos"],
  ["comparativas", "Comparativas y calibración"],
  ["comunidad", "Comunidad"],
  ["superposiciones", "Diálogos y pestañas"],
  ["pasos", "Flujo por pasos"],
  ["requisitos", "Requisitos pendientes"],
  ["movimiento", "Movimiento"],
] as const;
